"""
Repository protocols (ports) — implementations live in infrastructure (Adapter).

Keeping Protocol definitions here anchors UML "interface" diagrams for teammates.
"""

from datetime import date, datetime
from typing import Protocol

from gym_management.domain.equipment.equipment import Equipment
from gym_management.domain.equipment.maintenance_record import MaintenanceRecord
from gym_management.domain.equipment.repair_record import RepairRecord
from gym_management.domain.finance.budget import BudgetCategory, BudgetLine
from gym_management.domain.finance.payment import Payment
from gym_management.domain.membership.medical_report import MedicalReport
from gym_management.domain.membership.subscriber import Subscriber
from gym_management.domain.subscription.subscription import Subscription
from gym_management.domain.subscription.subscription_package import SubscriptionPackage


class MedicalReportRepository(Protocol):
    def add(self, report: MedicalReport) -> MedicalReport: ...
    def get(self, report_id: int) -> MedicalReport | None: ...
    def list_expiring_before(self, cutoff: date) -> list[MedicalReport]: ...
    def list_all(self) -> list[MedicalReport]: ...


class SubscriberRepository(Protocol):
    def add(self, subscriber: Subscriber) -> Subscriber: ...
    def get(self, subscriber_id: int) -> Subscriber | None: ...
    def list(self) -> list[Subscriber]: ...


class SubscriptionPackageRepository(Protocol):
    def add(self, package: SubscriptionPackage) -> SubscriptionPackage: ...
    def get(self, package_id: int) -> SubscriptionPackage | None: ...
    def list(self) -> list[SubscriptionPackage]: ...


class SubscriptionRepository(Protocol):
    def add(self, subscription: Subscription) -> Subscription: ...
    def get(self, subscription_id: int) -> Subscription | None: ...
    def list_for_subscriber(self, subscriber_id: int) -> list[Subscription]: ...
    def count_all(self) -> int: ...


class PaymentRepository(Protocol):
    def add(self, payment: Payment) -> Payment: ...
    def list_for_subscription(self, subscription_id: int) -> list[Payment]: ...
    def total_for_subscription(self, subscription_id: int) -> str: ...
    def total_between(self, start: datetime, end: datetime) -> str: ...


class BudgetLineRepository(Protocol):
    def upsert(self, line: BudgetLine) -> BudgetLine: ...
    def list_period(self, year: int, month: int) -> list[BudgetLine]: ...
    def get_line(
        self, year: int, month: int, category: BudgetCategory
    ) -> BudgetLine | None: ...


class EquipmentRepository(Protocol):
    def add(self, equipment: Equipment) -> Equipment: ...
    def get(self, equipment_id: int) -> Equipment | None: ...
    def list(self) -> list[Equipment]: ...


class MaintenanceRepository(Protocol):
    def add(self, record: MaintenanceRecord) -> MaintenanceRecord: ...
    def list_for_equipment(self, equipment_id: int) -> list[MaintenanceRecord]: ...
    def total_cost_between(self, start: date, end: date) -> str: ...


class RepairRepository(Protocol):
    def add(self, record: RepairRecord) -> RepairRecord: ...
    def list_for_equipment(self, equipment_id: int) -> list[RepairRecord]: ...
    def total_cost_between(self, start: date, end: date) -> str: ...
